import type { CityMetadata } from './CityTypes';

export const NIGERIA_CITIES_REGISTRY: Record<string, CityMetadata> = {
  lagos: {
    id: 'lagos',
    name: 'Lagos Island & Coastal Metropolis',
    state: 'Lagos State',
    zone: 'South West',
    tagline: 'Centre of Excellence • Commercial Capital of Africa',
    capital: false,
    climate: 'coastal_tropical',
    skyColorHex: 0x6eb7f2,
    fogColorHex: 0xa9d6f8,
    sunIntensity: 2.2,
    routes: [
      {
        destinationId: 'abuja',
        mode: 'flight',
        airlineOrOperator: 'Air Peace',
        flightOrBusCode: 'P47120 (Boeing 737-500)',
        fare: 35000,
        durationSeconds: 4,
        departureStation: 'Murtala Muhammed Airport (LOS Terminal 2)',
        arrivalStation: 'Nnamdi Azikiwe International Airport (ABV)',
        perkDescription: 'VIP Flight service, airline snack box, +35 Street Cred.',
        souvenirItem: {
          id: 'flight_ticket_abuja',
          name: 'Air Peace Lagos-Abuja Boarding Pass',
          icon: '🎫',
          description: 'Official Air Peace priority boarding pass for flight P47120.',
        },
      },
      {
        destinationId: 'abuja',
        mode: 'luxury_coach',
        airlineOrOperator: 'GIGM Executive Express',
        flightOrBusCode: 'GIG-709 Luxury Scania',
        fare: 12000,
        durationSeconds: 5,
        departureStation: 'Jibowu / Ojota Interstate Bus Terminal',
        arrivalStation: 'Utako Transport Hub, Abuja',
        perkDescription: 'Cross-country highway journey with roadside plantain & scenery.',
        souvenirItem: {
          id: 'gigm_coach_pass',
          name: 'GIGM Cross-Country Coach Ticket',
          icon: '🚌',
          description: 'Executive interstate air-conditioned bus pass with WiFi.',
        },
      },
      {
        destinationId: 'port_harcourt',
        mode: 'flight',
        airlineOrOperator: 'Air Peace Executive',
        flightOrBusCode: 'P47190 (Boeing 737-800)',
        fare: 38000,
        durationSeconds: 4,
        departureStation: 'Murtala Muhammed Airport (LOS Terminal 2)',
        arrivalStation: 'Port Harcourt International Airport (PHC Omagwa)',
        perkDescription: 'Flight into Garden City oil metropolis, authentic Bole & Fish souvenir, +40 Street Cred.',
        souvenirItem: {
          id: 'flight_ticket_ph',
          name: 'Air Peace Lagos-Port Harcourt Boarding Pass',
          icon: '🎫',
          description: 'Priority flight ticket into the Oil & Gas Capital.',
        },
      },
    ],
  },
  abuja: {
    id: 'abuja',
    name: 'Abuja Federal Capital Territory',
    state: 'Federal Capital Territory (FCT)',
    zone: 'North Central',
    tagline: 'Centre of Unity • Federal Seat of Power',
    capital: true,
    climate: 'savannah_highland',
    skyColorHex: 0x7dd3fc,
    fogColorHex: 0xbae6fd,
    sunIntensity: 2.4,
    routes: [
      {
        destinationId: 'lagos',
        mode: 'flight',
        airlineOrOperator: 'Ibom Air',
        flightOrBusCode: 'IAN-320 (Airbus A220)',
        fare: 35000,
        durationSeconds: 4,
        departureStation: 'Nnamdi Azikiwe Airport (ABV Domestic Wing)',
        arrivalStation: 'Murtala Muhammed Airport (LOS), Lagos',
        perkDescription: 'Smooth descent into Lagos coastal airspace, +35 Street Cred.',
        souvenirItem: {
          id: 'flight_ticket_lagos',
          name: 'Ibom Air Abuja-Lagos Boarding Pass',
          icon: '🎫',
          description: 'Official Ibom Air boarding pass for flight IAN-320.',
        },
      },
      {
        destinationId: 'lagos',
        mode: 'luxury_coach',
        airlineOrOperator: 'Young Shall Grow Motors',
        flightOrBusCode: 'YSG-Express Luxury Coach',
        fare: 12000,
        durationSeconds: 5,
        departureStation: 'Utako Terminal, Abuja',
        arrivalStation: 'Broad Street Danfo Terminus, Lagos',
        perkDescription: 'Night highway luxury bus with Afrobeats in-flight entertainment.',
        souvenirItem: {
          id: 'ysg_bus_ticket',
          name: 'Young Shall Grow Interstate Bus Ticket',
          icon: '🚌',
          description: 'Interstate coach ticket through Kogi and Edo states into Lagos.',
        },
      },
      {
        destinationId: 'port_harcourt',
        mode: 'flight',
        airlineOrOperator: 'United Nigeria Airlines',
        flightOrBusCode: 'UN-504 (Embraer 145)',
        fare: 36000,
        durationSeconds: 4,
        departureStation: 'Nnamdi Azikiwe Airport (ABV)',
        arrivalStation: 'Port Harcourt International (PHC)',
        perkDescription: 'Quick regional jet connecting capital to Niger Delta hub, +35 Street Cred.',
        souvenirItem: {
          id: 'ph_united_ticket',
          name: 'United Nigeria Abuja-PH Flight Pass',
          icon: '🎫',
          description: 'Direct flight ticket to Port Harcourt Garden City.',
        },
      },
    ],
  },
  port_harcourt: {
    id: 'port_harcourt',
    name: 'Port Harcourt (Garden City)',
    state: 'Rivers State',
    zone: 'South South',
    tagline: 'Treasure Base of the Nation • Oil & Gas Capital',
    capital: false,
    climate: 'delta_mangrove',
    skyColorHex: 0x64748b,
    fogColorHex: 0x94a3b8,
    sunIntensity: 2.1,
    routes: [
      {
        destinationId: 'lagos',
        mode: 'flight',
        airlineOrOperator: 'Air Peace',
        flightOrBusCode: 'P47191 (Boeing 737)',
        fare: 38000,
        durationSeconds: 4,
        departureStation: 'Port Harcourt International (PHC)',
        arrivalStation: 'Murtala Muhammed Airport (LOS), Lagos',
        perkDescription: 'Express return to Lagos Island, +35 Street Cred.',
        souvenirItem: {
          id: 'ph_bole_fish',
          name: 'Authentic Port Harcourt Bole & Roasted Fish',
          icon: '🐟',
          description: 'World-famous roasted plantain, spicy pepper sauce, and fresh grilled sea fish.',
        },
      },
      {
        destinationId: 'abuja',
        mode: 'flight',
        airlineOrOperator: 'Ibom Air',
        flightOrBusCode: 'IAN-410 (Airbus A220)',
        fare: 36000,
        durationSeconds: 4,
        departureStation: 'Port Harcourt International (PHC)',
        arrivalStation: 'Nnamdi Azikiwe International Airport (ABV), Abuja',
        perkDescription: 'Direct flight to the Federal Capital Territory, +35 Street Cred.',
        souvenirItem: {
          id: 'flight_ticket_ph_abv',
          name: 'Ibom Air PH-Abuja Boarding Pass',
          icon: '🎫',
          description: 'Boarding pass into the Three Arms Zone.',
        },
      },
    ],
  },
};
