import type { CityMetadata } from './CityTypes';

export const NIGERIA_CITIES_REGISTRY: Record<string, CityMetadata> = {
  lagos: {
    id: 'lagos',
    name: 'Lagos Island & Coastal Metropolis',
    state: 'Lagos State',
    zone: 'South West',
    tagline: 'Centre of Excellence • Commercial Capital of Africa',
    capital: false,
    climate: 'coastal_tropical',
    skyColorHex: 0x6eb7f2,
    fogColorHex: 0xa9d6f8,
    sunIntensity: 2.2,
    routes: [
      {
        destinationId: 'abuja',
        mode: 'flight',
        airlineOrOperator: 'Air Peace',
        flightOrBusCode: 'P47120 (Boeing 737-500)',
        fare: 35000,
        durationSeconds: 4,
        departureStation: 'Murtala Muhammed Airport (LOS Terminal 2)',
        arrivalStation: 'Nnamdi Azikiwe International Airport (ABV)',
        perkDescription: 'VIP Flight service, airline snack box, +35 Street Cred.',
        souvenirItem: {
          id: 'flight_ticket_abuja',
          name: 'Air Peace Lagos-Abuja Boarding Pass',
          icon: '🎫',
          description: 'Official Air Peace priority boarding pass for flight P47120.',
        },
      },
      {
        destinationId: 'abuja',
        mode: 'luxury_coach',
        airlineOrOperator: 'GIGM Executive Express',
        flightOrBusCode: 'GIG-709 Luxury Scania',
        fare: 12000,
        durationSeconds: 5,
        departureStation: 'Jibowu / Ojota Interstate Bus Terminal',
        arrivalStation: 'Utako Transport Hub, Abuja',
        perkDescription: 'Cross-country highway journey with roadside plantain & scenery.',
        souvenirItem: {
          id: 'gigm_coach_pass',
          name: 'GIGM Cross-Country Coach Ticket',
          icon: '🚌',
          description: 'Executive interstate air-conditioned bus pass with WiFi.',
        },
      },
    ],
  },
  abuja: {
    id: 'abuja',
    name: 'Abuja Federal Capital Territory',
    state: 'Federal Capital Territory (FCT)',
    zone: 'North Central',
    tagline: 'Centre of Unity • Federal Seat of Power',
    capital: true,
    climate: 'savannah_highland',
    skyColorHex: 0x7dd3fc, // Crisp high-altitude clear capital sky
    fogColorHex: 0xbae6fd,
    sunIntensity: 2.4,
    routes: [
      {
        destinationId: 'lagos',
        mode: 'flight',
        airlineOrOperator: 'Ibom Air',
        flightOrBusCode: 'IAN-320 (Airbus A220)',
        fare: 35000,
        durationSeconds: 4,
        departureStation: 'Nnamdi Azikiwe Airport (ABV Domestic Wing)',
        arrivalStation: 'Murtala Muhammed Airport (LOS), Lagos',
        perkDescription: 'Smooth descent into Lagos coastal airspace, +35 Street Cred.',
        souvenirItem: {
          id: 'flight_ticket_lagos',
          name: 'Ibom Air Abuja-Lagos Boarding Pass',
          icon: '🎫',
          description: 'Official Ibom Air boarding pass for flight IAN-320.',
        },
      },
      {
        destinationId: 'lagos',
        mode: 'luxury_coach',
        airlineOrOperator: 'Young Shall Grow Motors',
        flightOrBusCode: 'YSG-Express Luxury Coach',
        fare: 12000,
        durationSeconds: 5,
        departureStation: 'Utako Terminal, Abuja',
        arrivalStation: 'Broad Street Danfo Terminus, Lagos',
        perkDescription: 'Night highway luxury bus with Afrobeats in-flight entertainment.',
        souvenirItem: {
          id: 'ysg_bus_ticket',
          name: 'Young Shall Grow Interstate Bus Ticket',
          icon: '🚌',
          description: 'Interstate coach ticket through Kogi and Edo states into Lagos.',
        },
      },
    ],
  },
};
